### ISSUE TITLE
[Feature]: Forward `click` from `SplitterResizeHandle`

### ISSUE THREAD

**Issue by Barbapapazes** [unovue/radix-vue#1514]
### Describe the feature

Hello 👋,

I would love to handle a reset panel size when the user `dbclick` on the `SplitterResizeHandle` but it's not possible because the `click` and `dbclick` event is not forwarded.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hi @Barbapapazes ! The current does forward all the needed event, including double click. I think you might be capturing the wrong event, should `dblclick` instead of `dbclick`

https://stackblitz.com/edit/c63utr9r?file=src%2FApp.vue

https://developer.mozilla.org/en-US/docs/Web/API/Element/dblclick_event

**Comment by Barbapapazes** [comment]
Thanks! 🙌

It works but:

- The `ResizeHandle` must have a width
- The user must click on the `ResizeHandle`


https://github.com/user-attachments/assets/671315b9-3df8-4b47-9e59-fe0199543d98

In this recording, when I click on the `ResizeHandle`, the event is logged but if I'm just before (or after) it does not works but I can drag-n-drop panels. You can reproduce in your stackblitz.
